Stage 1 Fin
{"heavy_mg_maxim_m1910_30"
	("emplacement" side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(2) crew1(mg_crew:1) crew2(mg_crew_asst:1) condition(barricade) action(maxim_m1910_30))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_ds39_stand_fin"
	("emplacement" side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(2) crew1(mg_crew:1) crew2(mg_crew_asst:1) condition(barricade) action(ds39_stand_fin))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_panzernest_krab"
	("emplacement" side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(2) crew1(mg_crew:1) crew2(mg_crew_asst:1) condition(barricade) action(panzernest_krab))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_20mm_itk35"
	("emplacement"  side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(2) crew(artilleryman:2) condition(barricade) action(20mm_itk35))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_20mm_l39"
	("emplacement"  side(fin) period(mid) min_stage(3) max_stage(99) cw(0) cp(0) crew(artilleryman:2) condition(barricade) action(20mm_l39))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_37mm_pstk36"
	("emplacement"  side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(37mm_pstk36))
	{cost 1}{not_for_player_sale 1}
}
Stage 2 fin
{"heavy_mg_20mm_itk40"
	("emplacement"  side(fin) period(mid) min_stage(2) max_stage(99) cw(0) cp(0)  cd(2) crew(artilleryman:2) condition(barricade) action(20mm_itk40))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_40mm_itk38b"
	("emplacement"  side(fin) period(mid) min_stage(2) max_stage(99) cw(0) cp(0) cd(2) crew(artilleryman:3) condition(barricade) action(40mm_itk38b))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_75mm_itk37"
	("emplacement"  side(fin) period(mid) min_stage(4) max_stage(99) cw(0) cp(0) cd(2) crew(artilleryman:5) condition(barricade) action(75mm_itk37))
	{cost 1}{not_for_player_sale 1}
}


; AT WEAPONRY

{"heavy_mg_45mm_pstk32"
	("emplacement"  side(fin) period(mid) min_stage(5) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(45mm_pstk32))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_47mm_pstk39"
	("emplacement"  side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(47mm_pstk39))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_50mm_pstk38"
	("emplacement"  side(fin) period(mid) min_stage(4) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(50mm_pstk38))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_76mm_k02"
	("emplacement"  side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(76mm_k02))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_76mm_k02_30_40"
	("emplacement"  side(fin) period(mid) min_stage(3) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(76mm_k02_30_40))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_75mm_pstk9738"
	("emplacement"  side(fin) period(mid) min_stage(4) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(75mm_pstk9738))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_76mm_k36"
	("emplacement"  side(fin) period(mid) min_stage(4) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(76mm_k36))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_75mm_k40"
	("emplacement"  side(fin) period(mid) min_stage(5) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(75mm_k40))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_50mm_krh38"
	("emplacement"  side(fin) period(mid) min_stage(4) max_stage(99) cw(0) cp(0) crew(artilleryman:2) condition(barricade) action(50mm_krh38))
	{cost 180}{not_for_player_sale 1}
}
{"heavy_mg_81mm_krh36"
	("emplacement"  side(fin) period(mid) min_stage(2) max_stage(99) cw(0) cp(0) crew(artilleryman:2) condition(barricade) action(81mm_krh36))
	{cost 225}{not_for_player_sale 1}
}
Stage 3 fin


{"heavy_mg_105mm_k13"
	("emplacement"  side(fin) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) crew(artilleryman:4) condition(barricade) action(105mm_k13))
	{cost 730}{not_for_player_sale 1}
}



Stage 1 ger
{"heavy_mg_mg34"
	("emplacement" side(ger) period(mid) min_stage(3) max_stage(99) cw(0) cp(0) cd(2) crew(mgun_2:0) condition(barricade) action(heavy_mg_mg34))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_mg42"
	("emplacement" side(ger) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(mgun_2:0) condition(barricade) action(mg42_lafette))
	{cost 2}{not_for_player_sale 1}
}

{"heavy_mg_20mm_flak30"
	("emplacement" side(ger) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:2) condition(barricade) action(20mm_flak30))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_28mm_pzb41"
	("emplacement" side(ger) period(mid) min_stage(1) max_stage(6) cw(0) cp(0) cd(5) crew(artilleryman:3) condition(barricade) action(28mm_pzb41))
	{cost 14}{not_for_player_sale 1}
}
{"heavy_mg_37mm_pak36"
	("emplacement" side(ger) period(mid) min_stage(3) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(37mm_pak36))
	{cost 18}{not_for_player_sale 1}
}
{"heavy_mg_37mm_flak37"
	("emplacement" side(ger) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:3) condition(barricade) action(37mm_flak37))
	{cost 2}{not_for_player_sale 1}
}
Stage 2 
{"heavy_mg_47mm_pakt"
	("emplacement" side(ger) period(mid) min_stage(3) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(47mm_pakt))
	{cost 23}{not_for_player_sale 1}
}
{"heavy_mg_50mm_pak38"
	("emplacement" side(ger) period(mid) min_stage(6) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(50mm_pak38))
	{cost 27}{not_for_player_sale 1}
}

{"heavy_mg_75mm_pak40"
	("emplacement" side(ger) period(mid) min_stage(9) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(75mm_pak40))
	{cost 3}{not_for_player_sale 1} 
}
{"heavy_mg_75mm_leig18"
	("emplacement" side(ger) period(mid) min_stage(2) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(75mm_leig18))
	{cost 5}{not_for_player_sale 1}
}
{"heavy_mg_80mm_sgrw34"
	("emplacement" side(ger) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(rifleman_1:2) condition(barricade) action(80mm_sgrw34))
	{cost 5}{not_for_player_sale 1}
}
Stage 3
{"heavy_mg_88mm_flak18"
	("emplacement" side(ger) period(mid) min_stage(5) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:5) condition(barricade) action(88mm_flak18))
	{cost 5}{not_for_player_sale 1} 
}
{"heavy_mg_88mm_flak36"
	("emplacement" side(ger) period(mid) min_stage(5) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:5) condition(barricade) action(88mm_flak36))
	{cost 5}{not_for_player_sale 1}
}

{"heavy_mg_105mm_lefh18"
	("emplacement" side(ger) period(mid) min_stage(3) max_stage(99) cw(0) cp(0)  cd(5) crew(artilleryman:4) condition(barricade) action(105mm_lefh18))
	{cost 5}{not_for_player_sale 1}
}


Stage 1 sov
{"heavy_mg_maxim"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) crew(mgun_2:0) condition(barricade) action(heavy_mg_maxim))
	{cost 8}{not_for_player_sale 1} 
}
{"heavy_mg_maxim2"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(mgun_2:2) condition(barricade) action(maxim))
	{cost 2}{not_for_player_sale 1} 
}
{"heavy_mg_m41_ampulomet"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(rifleman_1:2) condition(barricade) action(m41_ampulomet))
	{cost 2}{not_for_player_sale 1}
}
{"heavy_mg_45mm_m37"
	("emplacement" side(rus) period(mid) min_stage(12) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(45mm_m37))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_25mm_72k"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:3) condition(barricade) action(25mm_72k))
	{cost 2}{not_for_player_sale 1}
}

Stage 2
{"heavy_mg_dshk_aa"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(mgun_2:2) condition(barricade) action(dshk_aa))
	{cost 12}{not_for_player_sale 1}
}
{"heavy_mg_dshk_stan"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(mgun_2:2) condition(barricade) action(dshk_stan))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_37mm_61k"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:3) condition(barricade) action(37mm_61k))
	{cost 2}{not_for_player_sale 1}
}
{"heavy_mg_45mm_m42"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(45mm_m42))
	{cost 1}{not_for_player_sale 1}
}
{"heavy_mg_57mm_zis2"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(57mm_zis2))
	{cost 3}{not_for_player_sale 1}
}
{"heavy_mg_76mm_f22"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(76mm_f22))
	{cost 2}{not_for_player_sale 1}
}
{"heavy_mg_76mm_zis3"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(76mm_zis3))
	{cost 2}{not_for_player_sale 1}
}
{"heavy_mg_82mm_bm37"
	("emplacement"  side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) crew(rifleman_1:2)condition(barricade) action(82mm_bm37))
	{cost 250}{not_for_player_sale 1}
}
{"heavy_mg_76mm_m43"
	("emplacement"  side(rus) period(mid) min_stage(6) max_stage(99) cw(0) cp(0) crew(artilleryman:4)condition(barricade) action(76mm_m43))
	{cost 350}{not_for_player_sale 1}
}
Stage 3



{"heavy_mg_85mm_52k"
	("emplacement" side(rus) period(mid) min_stage(1) max_stage(99) cw(0) cp(0) cd(5) crew(artilleryman:4) condition(barricade) action(85mm_52k))
	{cost 4}{not_for_player_sale 1}
}



{"heavy_mg_107mm_m1910_30"
	("emplacement"  side(rus) period(mid) min_stage(3) max_stage(99) cw(0) cp(0) crew(artilleryman:4)condition(barricade) action(107mm_m1910_30))
	{cost 400}{not_for_player_sale 1}
}





