			{"music_intense"}
			{"balance"}
			{"user_nation"}
			{"dcg_error"}
			{"dcg_on"}
			{"enemyid"}
			{"ai_air_on"}
			{"user_team"}
			{"def_team"}
			{"tier2"}
			{"arrows"}
			{"ai death count"}
			{"flag count"}
			{"player death count"}
			{"player tank count"}
			{"player arty count"}
			{"officeractions"}
			{"airscripts"}
			{"officerdocument"}
			{"officerdocument2"}
			{"partisan"}
			{"randomtimer"}
			{"defensetier"}
			{"radiocar"}
			{"readytodelete"}
			{"para_plane_side_start"}
			{"para_plane_index"}
			{"drop_behind_lines"}
			{"targeted_drop"}
			{"max_para_groups"}
			{"player_defending"}
			{"count_of_para_planes_using_waypoint"}
			{"static_ai_spawn_points"}
			{"disable_advanced_ai_pathing_logic"}
			{"ai_officer_callin_active"}
			{"ai_offmap_callin_id"}
			{"ai_offmap_priority_targeting"}
			{"player_drop_plane_index"}
			{"max_count_of_player_drop_planes"}
			{"move_ai_spawns_to_player_side"}
			{"early_stage_missions"}
			{"ai_call_big_bertha"}
			{"surrender_confirm_count"}