	{Entity "spawn_point" 0x8055
		{Position 585 935}
		{xform zl -109.81}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 273}
	}
	{Entity "spawn_point" 0x8056
		{Position -1590 -490}
		{xform zl 137.39}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 275}
	}
	{Entity "spawn_point" 0x8057
		{Position 2275 2765}
		{xform zl -153.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 293}
	}
	{Entity "spawn_point" 0x8058
		{Position 2795 -100}
		{xform zl 174.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 295}
	}
	{Entity "spawn_point" 0x8059
		{Position -1350 2880}
		{xform zl -153.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 313}
	}
	{Entity "spawn_point" 0x805a
		{Position 2275 2850}
		{xform zl -125.13}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 214}
	}
	{Entity "spawn_point" 0x805b
		{Position 555 1335}
		{xform zl -140.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 215}
	}
	{Entity "spawn_point" 0x82db
		{Position -1400 2600}
		{xform zl -94.54}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 216}
	}
	{Entity "spawn_point" 0x82dc
		{Position -1575 -730}
		{xform zl 174.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 217}
	}
	{Entity "spawn_point" 0x82dd
		{Position 2710 110}
		{xform zl 157.23}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 220}
	}
	{Entity "spawn_point" 0x8326
		{Position 2760 235}
		{xform zl 11.3}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 672}
	}
	{Entity "spawn_point" 0x8327
		{Position 2845 -30 150.77}
		{xform zl 174.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 673}
	}
	{Entity "spawn_point" 0x8328
		{Position 2835 -385}
		{xform zl 174.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 674}
	}
	{Entity "spawn_point" 0x832a
		{Position 2775 -270}
		{xform zl -19.33}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 675}
	}
	{Entity "spawn_point" 0x832b
		{Position 2400 -125 165.04}
		{xform zl 174.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 676}
	}
	{Entity "spawn_point" 0x832c
		{Position 2395 105 167.89}
		{xform zl 174.85}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 677}
	}
	{Entity "spawn_point" 0x832d
		{Position 2400 -15 183.55}
		{xform zl -19.84}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 678}
	}
	{Entity "spawn_point" 0x832e
		{Position 2360 250 91.06}
		{xform zl -24.52}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 679}
	}
	{Entity "spawn_point" 0x832f
		{Position -1580 -865}
		{xform zl 140.6}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 680}
	}
	{Entity "spawn_point" 0x8331
		{Position -1600 -1000}
		{xform zl 145.3}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 681}
	}
	{Entity "spawn_point" 0x8332
		{Position -1575 -615}
		{xform zl 129.74}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 682}
	}
	{Entity "spawn_point" 0x8334
		{Position -1625 -295}
		{xform zl 37.54}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 683}
	}
	{Entity "spawn_point" 0x8336
		{Position -1935 -420}
		{xform zl 174.82}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 684}
	}
	{Entity "spawn_point" 0x8337
		{Position -1870 -700}
		{xform zl -39.77}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 685}
	}
	{Entity "spawn_point" 0x8339
		{Position -1945 -525}
		{xform zl 37.54}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 686}
	}
	{Entity "spawn_point" 0x833a
		{Position -1990 -680}
		{xform zl 160.5}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 687}
	}
	{Entity "spawn_point" 0x833c
		{Position 2260 2650}
		{xform zl -153.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 688}
	}
	{Entity "spawn_point" 0x833e
		{Position 2265 2560}
		{xform zl -34.87}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 689}
	}
	{Entity "spawn_point" 0x833f
		{Position 2250 3050}
		{xform zl 33.09}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 690}
	}
	{Entity "spawn_point" 0x8341
		{Position 2235 2465}
		{xform zl -153.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 691}
	}
	{Entity "spawn_point" 0x8342
		{Position 1745 2680}
		{xform zl 160.89}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 692}
	}
	{Entity "spawn_point" 0x8343
		{Position 1720 2905}
		{xform zl -177.34}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 693}
	}
	{Entity "spawn_point" 0x8345
		{Position 1650 2750}
		{xform zl -34.87}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 694}
	}
	{Entity "spawn_point" 0x8346
		{Position 1690 2840}
		{xform zl -34.87}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 695}
	}
	{Entity "spawn_point" 0x8348
		{Position 590 1055}
		{xform zl 5.19}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 696}
	}
	{Entity "spawn_point" 0x834a
		{Position 595 1265}
		{xform zl 116.36}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 697}
	}
	{Entity "spawn_point" 0x834c
		{Position 585 1435}
		{xform zl 179.99}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 698}
	}
	{Entity "spawn_point" 0x834e
		{Position 635 1170}
		{xform zl -6.78}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 699}
	}
	{Entity "spawn_point" 0x834f
		{Position -90 1220}
		{xform zl -6.77}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 700}
	}
	{Entity "spawn_point" 0x8351
		{Position -35 1150}
		{xform zl -158.53}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 701}
	}
	{Entity "spawn_point" 0x8353
		{Position -65 1460}
		{xform zl -6.77}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 702}
	}
	{Entity "spawn_point" 0x8355
		{Position -40 1280}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 703}
	}
	{Entity "spawn_point" 0x8357
		{Position -1385 2660}
		{xform zl 110.58}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 704}
	}
	{Entity "spawn_point" 0x8358
		{Position -1365 2750}
		{xform zl -114.07}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 705}
	}
	{Entity "spawn_point" 0x835a
		{Position -1360 2835}
		{xform zl -130.67}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 706}
	}
	{Entity "spawn_point" 0x835c
		{Position -1350 2980}
		{xform zl 152.45}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 707}
	}
	{Entity "spawn_point" 0x835d
		{Position -1645 2865}
		{xform zl -144.64}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 708}
	}
	{Entity "spawn_point" 0x835f
		{Position -1590 2705}
		{xform zl -13.39}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 709}
	}
	{Entity "spawn_point" 0x8360
		{Position -1645 2940}
		{xform zl -0.58}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 710}
	}
	{Entity "spawn_point" 0x8361
		{Position -1615 2755}
		{xform zl -53.72}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 711}
	}
	{Entity "sandbag_watchtower" 0xf011
		{Position 6531.3 8486.34}
	}
	{Entity "spawn_point" 0x8009
		{Position 1115 1500}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 1}
	}
	{Entity "spawn_point" 0x800d
		{Position 1105 1355}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 2}
	}
	{Entity "spawn_point" 0x800e
		{Position 1100 1170}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3}
	}
	{Entity "spawn_point" 0x8011
		{Position 1085 1005}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 4}
	}
	{Entity "spawn_point" 0x8013
		{Position -1125 -550}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 5}
	}
	{Entity "spawn_point" 0x8016
		{Position -1065 -630}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 6}
	}
	{Entity "spawn_point" 0x8017
		{Position -1070 -815}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 7}
	}
	{Entity "spawn_point" 0x8027
		{Position -1085 -975}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 9}
	}
	{Entity "spawn_point" 0x8028
		{Position 2790 2540}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 13}
	}
	{Entity "spawn_point" 0x8029
		{Position 2805 3025}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 14}
	}
	{Entity "spawn_point" 0x802a
		{Position 2800 2840}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 17}
	}
	{Entity "spawn_point" 0x802e
		{Position 2785 2675}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 18}
	}
	{Entity "spawn_point" 0x802f
		{Position 3340 200}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 48}
	}
	{Entity "spawn_point" 0x8030
		{Position 3375 15}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 242}
	}
	{Entity "spawn_point" 0x8043
		{Position 3370 -170}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 243}
	}
	{Entity "spawn_point" 0x8044
		{Position 3310 -295}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 253}
	}
	{Entity "spawn_point" 0x8045
		{Position -1105 2985}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 254}
	}
	{Entity "spawn_point" 0x8046
		{Position -1075 2865}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 255}
	}
	{Entity "spawn_point" 0x8047
		{Position -1085 2750}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 256}
	}
	{Entity "spawn_point" 0x8048
		{Position -1070 2675}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 274}
	}
	{Tags "cmp_def" "1_b_2-3_mg" "1_a_2-3_mg" 0x8055}
	{Tags "cmp_def" "2_b_2-3_mg" "2_a_2-3_mg" 0x8056}
	{Tags "cmp_def" "3_b_2-3_mg" "3_a_2-3_mg" 0x8057}
	{Tags "cmp_def" "4_b_2-3_mg" "4_a_2-3_mg" 0x8058}
	{Tags "cmp_def" "5_b_2-3_mg"  "5_a_2-3_mg"0x8059}
	{Tags "cmp_def" "3_b_2-3_mg" "3_a_2-3_mg" 0x805a}
	{Tags "cmp_def" "1_b_2-3_mg" "1_a_2-3_mg" 0x805b}
	{Tags "cmp_def" "5_b_2-3_mg"  "5_a_2-3_mg"0x82db}
	{Tags "cmp_def" "2_b_2-3_mg" "2_a_2-3_mg" 0x82dc}
	{Tags "cmp_def" "4_b_2-3_mg" "4_a2-3_mg" 0x82dd}
	{Tags "4_b_2-3_mg" "cmp_def" "4_a_2-3_mg" 0x8326}
	{Tags "4_b_2-3_mg" "cmp_def" "4_a_2-3_mg" 0x8327}
	{Tags "4_b_2-3_mg" "cmp_def" "4_a_2-3_mg" 0x8328}
	{Tags "4_b_2-3_mg" "cmp_def" "4_a_2-3_mg" 0x832a}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x832b}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x832c}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x832d}
	{Tags "cmp_def" "4_b_3_mg" "4_a_3_mg" 0x832e}
	{Tags "2_b_2-3_mg" "cmp_def" "2_a_2-3_mg" 0x832f}
	{Tags "2_b_2-3_mg" "cmp_def" "2_a_2-3_mg" 0x8331}
	{Tags "2_b_2-3_mg" "cmp_def" "2_a_2-3_mg" 0x8332}
	{Tags "2_b_2-3_mg" "cmp_def" "2_a_2-3_mg" 0x8334}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" "2_a_3_mg" 0x8336}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x8337}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x8339}
	{Tags "cmp_def" "2_b_3_mg" "2_a_3_mg" 0x833a}
	{Tags "cmp_def" "3_b_2-3_mg" "3_a_2-3_mg" 0x833c}
	{Tags "cmp_def" "3_b_2-3_mg" "3_a_2-3_mg" 0x833e}
	{Tags "cmp_def" "3_b_2-3_mg" "3_a_2-3_mg" 0x833f}
	{Tags "cmp_def" "3_b_2-3_mg" "3_a_2-3_mg" 0x8341}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x8342}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x8343}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x8345}
	{Tags "cmp_def" "3_b_3_mg" "3_a_3_mg" 0x8346}
	{Tags "1_b_2-3_mg" "1_a_2-3_mg" "cmp_def" "1_a_2-3_mg" 0x8348}
	{Tags "1_b_2-3_mg" "1_a_2-3_mg" "cmp_def" "1_a_2-3_mg" 0x834a}
	{Tags "1_b_2-3_mg" "1_a_2-3_mg" "cmp_def" "1_a_2-3_mg" 0x834c}
	{Tags "1_b_2-3_mg" "1_a_2-3_mg" "cmp_def" "1_a_2-3_mg" 0x834e}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x834f}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x8351}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x8353}
	{Tags "cmp_def" "1_b_3_mg" "1_a_3_mg" 0x8355}
	{Tags "5_b_2-3_mg" "cmp_def" "5_a_2-3_mg" 0x8357}
	{Tags "5_b_2-3_mg" "cmp_def" "5_a_2-3_mg" 0x8358}
	{Tags "5_b_2-3_mg" "cmp_def" "5_a_2-3_mg" 0x835a}
	{Tags "5_b_2-3_mg" "cmp_def" "5_a_2-3_mg" 0x835c}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x835d}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x835f}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x8360}
	{Tags "cmp_def" "5_b_3_mg" "5_a_3_mg" 0x8361}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8009}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x800d}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x800e}
	{Tags "cmp_def" "1_b_1-3_mg" "1_a_1-3_mg" 0x8011}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8013}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8016}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8017}
	{Tags "cmp_def" "2_b_1-3_mg" "2_a_1-3_mg" 0x8027}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8028}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x8029}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x802a}
	{Tags "cmp_def" "3_b_1-3_mg" "3_a_1-3_mg" 0x802e}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x802f}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8030}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8043}
	{Tags "cmp_def" "4_b_1-3_mg" "4_a_1-3_mg" 0x8044}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x8045}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x8046}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x8047}
	{Tags "cmp_def" "5_b_1-3_mg" "5_a_1-3_mg" 0x8048}
		
	
