	{Entity "spawn_point" 0xcf38
		{Position -2390 -4105}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3957}
	}
	{Entity "spawn_point" 0xcf39
		{Position -2420 -4250}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3958}
	}
	{Entity "spawn_point" 0xcf3a
		{Position -2425 -4435}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3959}
	}
	{Entity "spawn_point" 0xcf3b
		{Position -2440 -4600}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3960}
	}
	{Entity "spawn_point" 0xcf3c
		{Position -2710 -4125}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3961}
	}
	{Entity "spawn_point" 0xcf3d
		{Position -2715 -4275}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3962}
	}
	{Entity "spawn_point" 0xcf3e
		{Position -2720 -4460}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3963}
	}
	{Entity "spawn_point" 0xcf3f
		{Position -2735 -4620}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3964}
	}
	{Entity "spawn_point" 0xcf40
		{Position -2975 -4315}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3965}
	}
	{Entity "spawn_point" 0xcf41
		{Position -2980 -4465}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3966}
	}
	{Entity "spawn_point" 0xcf42
		{Position -2985 -4650}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3967}
	}
	{Entity "spawn_point" 0xcf43
		{Position -3000 -4815}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3968}
	}
	{Entity "spawn_point" 0xcf44
		{Position -2575 -4865}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3969}
	}
	{Entity "spawn_point" 0xcf45
		{Position -2585 -5015}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3970}
	}
	{Entity "spawn_point" 0xcf46
		{Position -2590 -5200}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3971}
	}
	{Entity "spawn_point" 0xcf47
		{Position -2605 -5360}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3972}
	}
	{Entity "spawn_point" 0xcf48
		{Position -3295 -4330}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3973}
	}
	{Entity "spawn_point" 0xcf49
		{Position -3300 -4475}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3974}
	}
	{Entity "spawn_point" 0xcf4a
		{Position -3305 -4660}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3975}
	}
	{Entity "spawn_point" 0xcf4b
		{Position -3320 -4825}
		{xform zl -174.94}
		{Extender "spawn_point"
			{pos 0}
		}
		{Player 0}
		{MID 3976}
	}