        {waypoints "arty"
			{"10"
				{position 2855.82 1203.48 0}
				{radius 2000}
				{RandomPosition 1}
			}
			{"11"
				{position -3091.43 4143.39 0}
				{radius 2000}
				{RandomPosition 1}
			}
			{"7"
				{position -3753.03 -131.377 0}
				{radius 2000}
				{RandomPosition 1}
			}
			{"8"
				{position -606.938 -261.529 0}
				{radius 2000}
				{RandomPosition 1}
			}
			{"9"
				{position 3312.49 -3614.71 0}
				{radius 2000}
				{RandomPosition 1}
			}
		}
		{waypoints "smoke"
			{"12"
				{position -6079.33 510.257 0}
				{radius 1500}
			}
			{"13"
				{position -6783.79 -3766.03 0}
				{radius 1500}
			}
			{"14"
				{position -6091.22 4641.92 0}
				{radius 1500}
			}
			{"15"
				{position 5909.55 -3848.25 0}
				{radius 1500}
			}
			{"16"
				{position 5795.72 738.703 0}
				{radius 1500}
			}
			{"17"
				{position 5856.65 4548.12 0}
				{radius 1500}
			}
		}
		{waypoints "airdelete"
			{"18"
				{position 455.411 7758.69 0}
				{RandomPosition 1}
			}
			{"19"
				{position 139.211 7620.95 0}
				{radius 2000}
				{RandomPosition 1}
				{commands
					{"delete"}
				}
			}
		}
		{waypoints "aiwaypoints_spawn_a"
			{"100"
				{position -7994.24 -2367.27 0}
				{radius 400}
				{RandomPosition 1}
				{transition "101"}
			}
			{"101"
				{position -7127.38 -2383.18 0}
				{radius 400}
				{RandomPosition 1}
				{transition "102"}
			}
			{"102"
				{position -5077.44 -2309.18 0}
				{radius 400}
				{RandomPosition 1}
				{transition "103"}
			}
			{"103"
				{position -4214.64 -2506.16 0}
				{radius 400}
				{RandomPosition 1}
				{transition "104"}
				{transition "125"}
			}
			{"104"
				{position -3358.01 -3256.76 0}
				{radius 400}
				{RandomPosition 1}
				{transition "105"}
			}
			{"105"
				{position -1346.83 -4055.59 0}
				{radius 400}
				{RandomPosition 1}
				{transition "106"}
			}
			{"106"
				{position -639.105 -4173.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "107"}
			}
			{"107"
				{position 947.543 -4122.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "108"}
			}
			{"108"
				{position 1944.42 -4138.45 0}
				{radius 400}
				{RandomPosition 1}
				{transition "109"}
			}
			{"109"
				{position 3103.91 -4054.54 0}
				{radius 400}
				{RandomPosition 1}
				{transition "110"}
			}
			{"110"
				{position 5294.98 -3930.84 0}
				{radius 400}
				{RandomPosition 1}
				{transition "111"}
			}
			{"111"
				{position 5681.73 -2134.53 0}
				{radius 400}
				{RandomPosition 1}
				{transition "112"}
			}
			{"112"
				{position 5906.8 -1048.36 0}
				{radius 400}
				{RandomPosition 1}
				{transition "113"}
			}
			{"113"
				{position 5890.26 310.321 0}
				{radius 400}
				{RandomPosition 1}
				{transition "114"}
			}
			{"114"
				{position 5830.14 1649.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "115"}
			}
			{"115"
				{position 4733.71 2130.71 0}
				{radius 400}
				{RandomPosition 1}
				{transition "116"}
			}
			{"116"
				{position 4002.42 2321.11 0}
				{radius 400}
				{RandomPosition 1}
				{transition "117"}
			}
			{"117"
				{position 3310.08 2339.4 0}
				{radius 400}
				{RandomPosition 1}
				{transition "118"}
			}
			{"118"
				{position 2860.44 2011.55 0}
				{radius 400}
				{RandomPosition 1}
				{transition "119"}
			}
			{"119"
				{position 2153.64 1640.81 0}
				{radius 400}
				{RandomPosition 1}
				{transition "120"}
			}
			{"120"
				{position 1512.4 1626.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "121"}
			}
			{"121"
				{position 870.573 1560.91 0}
				{radius 400}
				{RandomPosition 1}
				{transition "122"}
			}
			{"122"
				{position 119.879 1483.45 0}
				{radius 400}
				{RandomPosition 1}
				{transition "123"}
			}
			{"123"
				{position -54.6938 1214.25 0}
				{radius 400}
				{RandomPosition 1}
				{transition "124"}
			}
			{"124"
				{position -124.676 857.178 0}
				{radius 400}
				{RandomPosition 1}
				{transition "29"}
			}
			{"125"
				{position -2928.43 -1573.28 0}
				{radius 400}
				{RandomPosition 1}
				{transition "126"}
			}
			{"126"
				{position -2390.75 -1142.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "127"}
				{transition "137"}
			}
			{"127"
				{position -1788.19 -666.975 0}
				{radius 400}
				{RandomPosition 1}
				{transition "128"}
			}
			{"128"
				{position -1250.32 -329.684 0}
				{radius 400}
				{RandomPosition 1}
				{transition "129"}
			}
			{"129"
				{position -763.139 -18.292 0}
				{radius 400}
				{RandomPosition 1}
				{transition "130"}
			}
			{"130"
				{position -514.078 405.844 0}
				{radius 400}
				{RandomPosition 1}
				{transition "131"}
			}
			{"131"
				{position -161.494 601.919 0}
				{radius 400}
				{RandomPosition 1}
				{transition "132"}
			}
			{"132"
				{position 226.338 712.071 0}
				{radius 400}
				{RandomPosition 1}
				{transition "133"}
			}
			{"133"
				{position 632.797 797.989 0}
				{radius 400}
				{RandomPosition 1}
				{transition "134"}
			}
			{"134"
				{position 1001.79 938.092 0}
				{radius 400}
				{RandomPosition 1}
				{transition "135"}
			}
			{"135"
				{position 1564.63 1215.81 0}
				{radius 400}
				{RandomPosition 1}
				{transition "136"}
			}
			{"136"
				{position 1830.72 1220.48 0}
				{radius 400}
				{RandomPosition 1}
				{transition "28"}
			}
			{"137"
				{position -1631.45 -1365.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "138"}
			}
			{"138"
				{position -916.867 -1577.27 0}
				{radius 400}
				{RandomPosition 1}
				{transition "139"}
			}
			{"139"
				{position -472.963 -1640.37 0}
				{radius 400}
				{RandomPosition 1}
				{transition "140"}
			}
			{"140"
				{position -101.713 -1723.84 0}
				{radius 400}
				{RandomPosition 1}
				{transition "141"}
			}
			{"141"
				{position 1385.7 -1669.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "142"}
			}
			{"142"
				{position 1989.91 -1625.9 0}
				{radius 400}
				{RandomPosition 1}
				{transition "143"}
			}
			{"143"
				{position 2650.12 -1647.07 0}
				{radius 400}
				{RandomPosition 1}
				{transition "144"}
			}
			{"144"
				{position 3178.79 -1677.51 0}
				{radius 400}
				{RandomPosition 1}
				{transition "145"}
				{transition "112"}
			}
			{"145"
				{position 3469.07 -1821.55 0}
				{radius 400}
				{RandomPosition 1}
				{transition "146"}
			}
			{"146"
				{position 3687.27 -2138.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "147"}
			}
			{"147"
				{position 4044.12 -2542.05 0}
				{radius 400}
				{RandomPosition 1}
				{transition "230"}
			}
			{"148"
				{position -8886.28 -1189.08 0}
				{radius 400}
				{RandomPosition 1}
				{transition "149"}
			}
			{"149"
				{position -7701.78 -998.016 0}
				{radius 400}
				{RandomPosition 1}
				{transition "150"}
			}
			{"150"
				{position -6849.45 -903.267 0}
				{radius 400}
				{RandomPosition 1}
				{transition "151"}
			}
			{"151"
				{position -6233.23 -838.252 0}
				{radius 400}
				{RandomPosition 1}
				{transition "152"}
			}
			{"152"
				{position -5482.52 -445.447 0}
				{radius 400}
				{RandomPosition 1}
				{transition "153"}
			}
			{"153"
				{position -4437.95 -198.18 0}
				{radius 400}
				{RandomPosition 1}
				{transition "154"}
			}
			{"154"
				{position -3928.99 5.52118 0}
				{radius 400}
				{RandomPosition 1}
				{transition "155"}
			}
			{"155"
				{position -3250.37 241.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "156"}
			}
			{"156"
				{position -2543.34 501.996 0}
				{radius 400}
				{RandomPosition 1}
				{transition "157"}
			}
			{"157"
				{position -1812.79 798.671 0}
				{radius 400}
				{RandomPosition 1}
				{transition "158"}
			}
			{"158"
				{position -1534.53 1180.95 0}
				{radius 400}
				{RandomPosition 1}
				{transition "159"}
			}
			{"159"
				{position -1271.31 1614.01 0}
				{radius 400}
				{RandomPosition 1}
				{transition "160"}
			}
			{"160"
				{position -10.7493 1663.73 0}
				{radius 400}
				{RandomPosition 1}
				{transition "161"}
			}
			{"161"
				{position 1081.62 1729.06 0}
				{radius 400}
				{RandomPosition 1}
				{transition "162"}
			}
			{"162"
				{position 1885.71 1679.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "163"}
				{transition "184"}
			}
			{"163"
				{position 2422.5 2050.88 0}
				{radius 400}
				{RandomPosition 1}
				{transition "164"}
			}
			{"164"
				{position 2456.26 2530.36 0}
				{radius 400}
				{RandomPosition 1}
				{transition "165"}
			}
			{"165"
				{position 2450.54 3053.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "166"}
			}
			{"166"
				{position 2203.87 3439.99 0}
				{radius 400}
				{RandomPosition 1}
				{transition "167"}
			}
			{"167"
				{position 1779 3619.19 0}
				{radius 400}
				{RandomPosition 1}
				{transition "168"}
			}
			{"168"
				{position 1287.66 3737.76 0}
				{radius 400}
				{RandomPosition 1}
				{transition "169"}
			}
			{"169"
				{position 17.6929 3745.98 0}
				{radius 400}
				{RandomPosition 1}
				{transition "170"}
			}
			{"170"
				{position -1719.69 3697.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "171"}
			}
			{"171"
				{position -2495.04 3788.61 0}
				{radius 400}
				{RandomPosition 1}
				{transition "31"}
			}
			{"172"
				{position -8798.18 711.132 0}
				{radius 400}
				{RandomPosition 1}
				{transition "173"}
			}
			{"173"
				{position -8226.47 501.381 0}
				{radius 400}
				{RandomPosition 1}
				{transition "174"}
			}
			{"174"
				{position -7591.01 75.3224 0}
				{radius 400}
				{RandomPosition 1}
				{transition "175"}
			}
			{"175"
				{position -7052.8 -92.8705 0}
				{radius 400}
				{RandomPosition 1}
				{transition "176"}
			}
			{"176"
				{position -6005.39 23.0714 0}
				{radius 400}
				{RandomPosition 1}
				{transition "177"}
				{transition "195"}
			}
			{"177"
				{position -5230.07 553.001 0}
				{radius 400}
				{RandomPosition 1}
				{transition "178"}
			}
			{"178"
				{position -4291.22 1171.72 0}
				{radius 400}
				{RandomPosition 1}
				{transition "179"}
			}
			{"179"
				{position -3877.49 1422.45 0}
				{radius 400}
				{RandomPosition 1}
				{transition "180"}
			}
			{"180"
				{position -3400.87 1593.2 0}
				{radius 400}
				{RandomPosition 1}
				{transition "181"}
			}
			{"181"
				{position -2372.55 1678.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "182"}
			}
			{"182"
				{position -1743.2 1612.73 0}
				{radius 400}
				{RandomPosition 1}
				{transition "183"}
			}
			{"183"
				{position -1407.73 1621.58 0}
				{radius 400}
				{RandomPosition 1}
				{transition "159"}
			}
			{"184"
				{position 2692.71 1808.1 0}
				{radius 400}
				{RandomPosition 1}
				{transition "185"}
			}
			{"185"
				{position 3133.62 1744.08 0}
				{radius 400}
				{RandomPosition 1}
				{transition "186"}
			}
			{"186"
				{position 3848.65 1673.05 0}
				{radius 400}
				{RandomPosition 1}
				{transition "187"}
			}
			{"187"
				{position 4959.38 1568.11 0}
				{radius 400}
				{RandomPosition 1}
				{transition "188"}
			}
			{"188"
				{position 5972.96 1381.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "189"}
			}
			{"189"
				{position 6841.94 1161.72 0}
				{radius 400}
				{RandomPosition 1}
				{transition "190"}
			}
			{"190"
				{position 7636.85 441.582 0}
				{radius 400}
				{RandomPosition 1}
				{transition "191"}
			}
			{"191"
				{position 8080.54 -139.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "192"}
			}
			{"192"
				{position 7979.1 -664.228 0}
				{radius 400}
				{RandomPosition 1}
				{transition "193"}
			}
			{"193"
				{position 7531.04 -1245.4 0}
				{radius 400}
				{RandomPosition 1}
				{transition "194"}
			}
			{"194"
				{position 6677.23 -1515.83 0}
				{radius 400}
				{RandomPosition 1}
				{transition "147"}
			}
			{"195"
				{position -5550.37 -405.514 0}
				{radius 400}
				{RandomPosition 1}
				{transition "196"}
			}
			{"196"
				{position -5188.31 -570.648 0}
				{radius 400}
				{RandomPosition 1}
				{transition "197"}
			}
			{"197"
				{position -4509.36 -654.043 0}
				{radius 400}
				{RandomPosition 1}
				{transition "198"}
			}
			{"198"
				{position -3737.15 -705.063 0}
				{radius 400}
				{RandomPosition 1}
				{transition "199"}
			}
			{"199"
				{position -2489 -806.611 0}
				{radius 400}
				{RandomPosition 1}
				{transition "200"}
			}
			{"200"
				{position -1396.37 -934.972 0}
				{radius 400}
				{RandomPosition 1}
				{transition "201"}
			}
			{"201"
				{position -490.804 -931.198 0}
				{radius 400}
				{RandomPosition 1}
				{transition "202"}
			}
			{"202"
				{position 118.677 -952.8 0}
				{radius 400}
				{RandomPosition 1}
				{transition "203"}
			}
			{"203"
				{position 1143.13 -778.141 0}
				{radius 400}
				{RandomPosition 1}
				{transition "204"}
			}
			{"204"
				{position 1885.81 -802.785 0}
				{radius 400}
				{RandomPosition 1}
				{transition "143"}
			}
			{"205"
				{position -8662.88 1404.11 0}
				{radius 400}
				{RandomPosition 1}
				{transition "206"}
			}
			{"206"
				{position -7936.99 1420.69 0}
				{radius 400}
				{RandomPosition 1}
				{transition "207"}
			}
			{"207"
				{position -7017.66 1472.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "208"}
			}
			{"208"
				{position -5626.95 1905.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "209"}
			}
			{"209"
				{position -4530.99 2354.05 0}
				{radius 400}
				{RandomPosition 1}
				{transition "210"}
			}
			{"210"
				{position -3947.89 2748.19 0}
				{radius 400}
				{RandomPosition 1}
				{transition "211"}
			}
			{"211"
				{position -3570.92 3094.16 0}
				{radius 400}
				{RandomPosition 1}
				{transition "31"}
			}
			{"212"
				{position -8808.72 5559.45 0}
				{radius 400}
				{RandomPosition 1}
				{transition "213"}
			}
			{"213"
				{position -8101.18 5944.5 0}
				{radius 400}
				{RandomPosition 1}
				{transition "214"}
			}
			{"214"
				{position -7358.09 5942.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "215"}
			}
			{"215"
				{position -5329.03 5836.44 0}
				{radius 400}
				{RandomPosition 1}
				{transition "216"}
				{transition "258"}
			}
			{"216"
				{position -4423.17 5830.07 0}
				{radius 400}
				{RandomPosition 1}
				{transition "217"}
			}
			{"217"
				{position -3473.66 5854.56 0}
				{radius 400}
				{RandomPosition 1}
				{transition "218"}
			}
			{"218"
				{position -2698.01 5846.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "219"}
			}
			{"219"
				{position -1828.84 5681.06 0}
				{radius 400}
				{RandomPosition 1}
				{transition "220"}
			}
			{"220"
				{position -226.616 5796.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "221"}
			}
			{"221"
				{position 574.284 5717.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "222"}
			}
			{"222"
				{position 1917.17 5709.44 0}
				{radius 400}
				{RandomPosition 1}
				{transition "223"}
			}
			{"223"
				{position 3748.03 5586.81 0}
				{radius 400}
				{RandomPosition 1}
				{transition "224"}
			}
			{"224"
				{position 5243.09 5507.58 0}
				{radius 400}
				{RandomPosition 1}
				{transition "225"}
			}
			{"225"
				{position 6205.39 5193.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "226"}
			}
			{"226"
				{position 7359.18 4364.45 0}
				{radius 400}
				{RandomPosition 1}
				{transition "227"}
				{transition "233"}
			}
			{"227"
				{position 7571.74 3586.56 0}
				{radius 400}
				{RandomPosition 1}
				{transition "228"}
			}
			{"228"
				{position 7957.03 2309.4 0}
				{radius 400}
				{RandomPosition 1}
				{transition "229"}
			}
			{"229"
				{position 8350.48 756.169 0}
				{radius 400}
				{RandomPosition 1}
				{transition "231"}
			}
			{"230"
				{position 3505.47 -3066.29 0}
				{radius 400}
				{RandomPosition 1}
				{transition "28"}
				{transition "32"}
				{commands
					{"entity_state"
						{tag_add freeroam}
					}
					{"delay"
						{time 1}
					}
					{"if"
						{condition
							{type cmp_i}
							{var "player_defending$"}
							{op "=="}
							{value 1}
						}
						{"action"
							{drop orders}
							{action advance}
							{target
								{source advanced}
								{group
									{select
										{tag
											{tag player}
										}
										{tag
											{tag player_veh}
										}
										{tag
											{tag player_armor}
										}
										{tag
											{tag player_car}
										}
									}
									{include
										{state
											{state operatable}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{group
									{select
										{zone
											{zone "gamezone"}
										}
									}
									{include
										{state
											{state operatable}
										}
										{relation
											{relation ally}
											{player "1"}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{amount 1
								}
							}
						}
					}
					{"if"
						{condition
							{type cmp_i}
							{var "player_defending$"}
							{op "=="}
							{value 0}
						}
						{"action"
							{drop orders}
							{action advance}
							{target
								{source advanced}
								{group
									{select
										{tag
											{tag player}
										}
										{tag
											{tag player_veh}
										}
										{tag
											{tag player_armor}
										}
										{tag
											{tag player_car}
										}
									}
									{include
										{state
											{state operatable}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{group
									{select
										{zone
											{zone "gamezone"}
										}
									}
									{include
										{relation
											{relation enemy}
											{player "1"}
										}
										{state
											{state operatable}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{amount 1
								}
							}
						}
					}
				}
			}
			{"231"
				{position 8439.72 -595.88 0}
				{radius 400}
				{RandomPosition 1}
				{transition "232"}
			}
			{"232"
				{position 8258.6 -1714.52 0}
				{radius 400}
				{RandomPosition 1}
				{transition "67"}
			}
			{"233"
				{position 6514.65 3558.6 0}
				{radius 400}
				{RandomPosition 1}
				{transition "234"}
			}
			{"234"
				{position 6020.77 3358.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "235"}
				{transition "241"}
			}
			{"235"
				{position 5209.67 3378.7 0}
				{radius 400}
				{RandomPosition 1}
				{transition "236"}
			}
			{"236"
				{position 4712.67 3228.07 0}
				{radius 400}
				{RandomPosition 1}
				{transition "237"}
			}
			{"237"
				{position 4270.72 3002.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "238"}
			}
			{"238"
				{position 3795 2660.75 0}
				{radius 400}
				{RandomPosition 1}
				{transition "239"}
			}
			{"239"
				{position 3133.59 2218.02 0}
				{radius 400}
				{RandomPosition 1}
				{transition "240"}
			}
			{"240"
				{position 2631.64 1579.76 0}
				{radius 400}
				{RandomPosition 1}
				{transition "28"}
			}
			{"241"
				{position 5572.44 2244.69 0}
				{radius 400}
				{RandomPosition 1}
				{transition "242"}
			}
			{"242"
				{position 5179.19 1719.24 0}
				{radius 400}
				{RandomPosition 1}
				{transition "243"}
			}
			{"243"
				{position 4646.69 992.896 0}
				{radius 400}
				{RandomPosition 1}
				{transition "244"}
			}
			{"244"
				{position 4327.83 235.485 0}
				{radius 400}
				{RandomPosition 1}
				{transition "245"}
			}
			{"245"
				{position 4230.37 -310.622 0}
				{radius 400}
				{RandomPosition 1}
				{transition "246"}
			}
			{"246"
				{position 4244.27 -1284.15 0}
				{radius 400}
				{RandomPosition 1}
				{transition "147"}
			}
			{"248"
				{position -8826.93 4541.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "250"}
			}
			{"250"
				{position -8200.13 4247.53 0}
				{radius 400}
				{RandomPosition 1}
				{transition "251"}
			}
			{"251"
				{position -7495.57 4075.4 0}
				{radius 400}
				{RandomPosition 1}
				{transition "252"}
				{transition "469"}
			}
			{"252"
				{position -6457.88 3960.96 0}
				{radius 400}
				{RandomPosition 1}
				{transition "253"}
				{transition "217"}
			}
			{"253"
				{position -5208.45 3818.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "254"}
			}
			{"254"
				{position -4304.72 3727.33 0}
				{radius 400}
				{RandomPosition 1}
				{transition "255"}
			}
			{"255"
				{position -3345.8 4052.6 0}
				{radius 400}
				{RandomPosition 1}
				{transition "256"}
			}
			{"256"
				{position -2726.55 4111.85 0}
				{radius 400}
				{RandomPosition 1}
				{transition "257"}
			}
			{"257"
				{position -2264.84 4067.91 0}
				{radius 400}
				{RandomPosition 1}
				{transition "258"}
			}
			{"258"
				{position -1484.48 4184.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "259"}
			}
			{"259"
				{position -663.971 3926.03 0}
				{radius 400}
				{RandomPosition 1}
				{transition "260"}
			}
			{"260"
				{position -517.725 3576.65 0}
				{radius 400}
				{RandomPosition 1}
				{transition "261"}
			}
			{"261"
				{position -430.715 3153.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "262"}
			}
			{"262"
				{position -305.74 2673.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "309"}
			}
			{"28"
				{position 2409.13 1071.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "230"}
				{transition "30"}
			}
			{"29"
				{position -375.67 111.456 0}
				{radius 400}
				{RandomPosition 1}
				{transition "30"}
			}
			{"30"
				{position -348.006 92.424 0}
				{radius 400}
				{RandomPosition 1}
				{transition "31"}
				{transition "28"}
			}
			{"309"
				{position -245.897 2314.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "310"}
			}
			{"31"
				{position -3197.06 3470.8 0}
				{radius 400}
				{RandomPosition 1}
				{transition "32"}
				{transition "29"}
			}
			{"310"
				{position -218.93 2011.49 0}
				{radius 400}
				{RandomPosition 1}
				{transition "29"}
			}
			{"32"
				{position -3027.41 659.618 0}
				{radius 400}
				{RandomPosition 1}
				{transition "230"}
				{transition "31"}
			}
			{"33"
				{position -8819.08 -5144.52 0}
				{radius 400}
				{RandomPosition 1}
				{transition "35"}
			}
			{"35"
				{position -7811.26 -5273.39 0}
				{radius 400}
				{RandomPosition 1}
				{transition "37"}
			}
			{"37"
				{position -6534.5 -5386.29 0}
				{radius 400}
				{RandomPosition 1}
				{transition "38"}
			}
			{"38"
				{position -4317.1 -5332.6 0}
				{radius 400}
				{RandomPosition 1}
				{transition "39"}
			}
			{"39"
				{position -2913.56 -5474.47 0}
				{radius 400}
				{RandomPosition 1}
				{transition "40"}
			}
			{"40"
				{position -1911.46 -5461.78 0}
				{radius 400}
				{RandomPosition 1}
				{transition "41"}
				{transition "84"}
			}
			{"41"
				{position -507.583 -5462.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "42"}
			}
			{"42"
				{position 1197.84 -5292.08 0}
				{radius 400}
				{RandomPosition 1}
				{transition "43"}
			}
			{"43"
				{position 2112.51 -5338.14 0}
				{radius 400}
				{RandomPosition 1}
				{transition "44"}
				{transition "58"}
			}
			{"44"
				{position 3202.15 -5395.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "45"}
			}
			{"45"
				{position 4740.26 -5481.48 0}
				{radius 400}
				{RandomPosition 1}
				{transition "46"}
			}
			{"46"
				{position 6195.54 -5503.64 0}
				{radius 400}
				{RandomPosition 1}
				{transition "47"}
			}
			{"469"
				{position -6759.2 3188.46 0}
				{radius 400}
				{RandomPosition 1}
				{transition "471"}
			}
			{"47"
				{position 7227.71 -5414.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "48"}
			}
			{"471"
				{position -6352.18 2716.49 0}
				{radius 400}
				{RandomPosition 1}
				{transition "473"}
			}
			{"473"
				{position -5962.3 2317.72 0}
				{radius 400}
				{RandomPosition 1}
				{transition "475"}
			}
			{"475"
				{position -5334.79 2058.77 0}
				{radius 400}
				{RandomPosition 1}
				{transition "477"}
			}
			{"477"
				{position -4871.01 1897.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "479"}
			}
			{"479"
				{position -4466.36 1834.68 0}
				{radius 400}
				{RandomPosition 1}
				{transition "481"}
			}
			{"48"
				{position 7726.79 -3951.1 0}
				{radius 400}
				{RandomPosition 1}
				{transition "49"}
				{transition "65"}
			}
			{"481"
				{position -4283.53 1652.91 0}
				{radius 400}
				{RandomPosition 1}
				{transition "32"}
			}
			{"49"
				{position 7693.35 -2719.98 0}
				{radius 400}
				{RandomPosition 1}
				{transition "51"}
			}
			{"50"
				{position 7492.29 -1600.4 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"51"
				{position 7688.33 -1567.9 0}
				{radius 400}
				{RandomPosition 1}
				{transition "52"}
			}
			{"52"
				{position 7504.35 -239.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "53"}
			}
			{"53"
				{position 6661.71 216.473 0}
				{radius 400}
				{RandomPosition 1}
				{transition "54"}
			}
			{"54"
				{position 5893.17 464.427 0}
				{radius 400}
				{RandomPosition 1}
				{transition "55"}
			}
			{"55"
				{position 5204.24 584.03 0}
				{radius 400}
				{RandomPosition 1}
				{transition "56"}
			}
			{"56"
				{position 4581.14 680.263 0}
				{radius 400}
				{RandomPosition 1}
				{transition "57"}
			}
			{"57"
				{position 3997.35 690.752 0}
				{radius 400}
				{RandomPosition 1}
				{transition "28"}
			}
			{"58"
				{position 2575.58 -4953.74 0}
				{radius 400}
				{RandomPosition 1}
				{transition "59"}
			}
			{"59"
				{position 2684.06 -4481.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "60"}
			}
			{"60"
				{position 2733.54 -3881.71 0}
				{radius 400}
				{RandomPosition 1}
				{transition "61"}
			}
			{"61"
				{position 2881.46 -3075.01 0}
				{radius 400}
				{RandomPosition 1}
				{transition "62"}
			}
			{"62"
				{position 2798.92 -2358.69 0}
				{radius 400}
				{RandomPosition 1}
				{transition "63"}
			}
			{"63"
				{position 2770.03 -1354.44 0}
				{radius 400}
				{RandomPosition 1}
				{transition "64"}
			}
			{"64"
				{position 2720.54 -706.395 0}
				{radius 400}
				{RandomPosition 1}
				{transition "28"}
			}
			{"65"
				{position 7157.62 -3582.31 0}
				{radius 400}
				{RandomPosition 1}
				{transition "66"}
			}
			{"66"
				{position 6599.27 -3221.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "67"}
			}
			{"67"
				{position 5968.56 -3177.79 0}
				{radius 400}
				{RandomPosition 1}
				{transition "68"}
			}
			{"68"
				{position 5447.89 -3153.81 0}
				{radius 400}
				{RandomPosition 1}
				{transition "69"}
			}
			{"69"
				{position 4865.59 -3130.52 0}
				{radius 400}
				{RandomPosition 1}
				{transition "230"}
			}
			{"70"
				{position -8947.55 -4592.75 0}
				{radius 400}
				{RandomPosition 1}
				{transition "71"}
			}
			{"71"
				{position -8372.13 -4052 0}
				{radius 400}
				{RandomPosition 1}
				{transition "72"}
			}
			{"72"
				{position -6892.97 -3619.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "73"}
			}
			{"73"
				{position -5542.51 -3337.47 0}
				{radius 400}
				{RandomPosition 1}
				{transition "74"}
			}
			{"74"
				{position -4352.9 -3166.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "75"}
			}
			{"75"
				{position -3524.99 -2885.11 0}
				{radius 400}
				{RandomPosition 1}
				{transition "76"}
				{transition "86"}
			}
			{"76"
				{position -2150.66 -2959.63 0}
				{radius 400}
				{RandomPosition 1}
				{transition "77"}
				{transition "42"}
			}
			{"77"
				{position -1167.32 -2867.27 0}
				{radius 400}
				{RandomPosition 1}
				{transition "78"}
			}
			{"78"
				{position -659.505 -2904.2 0}
				{radius 400}
				{RandomPosition 1}
				{transition "79"}
			}
			{"79"
				{position -176.314 -2906.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "80"}
			}
			{"80"
				{position 237.291 -2890.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "81"}
			}
			{"81"
				{position 734.957 -2764.51 0}
				{radius 400}
				{RandomPosition 1}
				{transition "82"}
			}
			{"82"
				{position 1192.54 -2805.19 0}
				{radius 400}
				{RandomPosition 1}
				{transition "83"}
			}
			{"83"
				{position 1764.18 -2795.11 0}
				{radius 400}
				{RandomPosition 1}
				{transition "84"}
			}
			{"84"
				{position 2432.11 -2995.28 0}
				{radius 400}
				{RandomPosition 1}
				{transition "85"}
			}
			{"85"
				{position 2663.79 -3030.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "61"}
			}
			{"86"
				{position -3023.81 -2524.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "87"}
			}
			{"87"
				{position -2716.89 -2286.19 0}
				{radius 400}
				{RandomPosition 1}
				{transition "88"}
			}
			{"88"
				{position -2082.58 -2033.14 0}
				{radius 400}
				{RandomPosition 1}
				{transition "89"}
			}
			{"89"
				{position -1589.57 -2035.42 0}
				{radius 400}
				{RandomPosition 1}
				{transition "90"}
			}
			{"90"
				{position -1073.3 -1950.57 0}
				{radius 400}
				{RandomPosition 1}
				{transition "91"}
			}
			{"91"
				{position -657.161 -1782.72 0}
				{radius 400}
				{RandomPosition 1}
				{transition "92"}
			}
			{"92"
				{position -389.136 -1585.81 0}
				{radius 400}
				{RandomPosition 1}
				{transition "93"}
			}
			{"93"
				{position -191.845 -1354.77 0}
				{radius 400}
				{RandomPosition 1}
				{transition "94"}
			}
			{"94"
				{position -129.02 -987.834 0}
				{radius 400}
				{RandomPosition 1}
				{transition "95"}
			}
			{"95"
				{position -165.201 -762.256 0}
				{radius 400}
				{RandomPosition 1}
				{transition "96"}
			}
			{"96"
				{position -273.599 -623.606 0}
				{radius 400}
				{RandomPosition 1}
				{transition "97"}
			}
			{"97"
				{position -196.614 -396.201 0}
				{radius 400}
				{RandomPosition 1}
				{transition "98"}
			}
			{"98"
				{position -36.7122 42.5336 0}
				{radius 400}
				{RandomPosition 1}
				{transition "29"}
			}
			{"99"
				{position -9088.08 -1905.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "100"}
			}
		}
		{waypoints "aiwaypoints_spawn_b"
			{"263"
				{position 2389.22 1068.14 0}
				{radius 400}
				{RandomPosition 1}
				{transition "264"}
				{transition "308"}
			}
			{"264"
				{position -333.424 227.498 0}
				{radius 400}
				{RandomPosition 1}
				{transition "265"}
				{transition "263"}
			}
			{"265"
				{position -3264.84 3511.39 0}
				{radius 400}
				{RandomPosition 1}
				{transition "266"}
				{transition "264"}
			}
			{"266"
				{position -3019.11 752.489 0}
				{radius 400}
				{RandomPosition 1}
				{transition "308"}
				{transition "265"}
			}
			{"267"
				{position 8166.18 -5216.1 0}
				{radius 400}
				{RandomPosition 1}
				{transition "268"}
			}
			{"268"
				{position 6550.85 -5350.76 0}
				{radius 400}
				{RandomPosition 1}
				{transition "269"}
			}
			{"269"
				{position 5425.86 -5340.05 0}
				{radius 400}
				{RandomPosition 1}
				{transition "270"}
			}
			{"270"
				{position 4064.48 -5472.1 0}
				{radius 400}
				{RandomPosition 1}
				{transition "271"}
			}
			{"271"
				{position 3075.63 -5390.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "272"}
			}
			{"272"
				{position 1753.54 -5286.29 0}
				{radius 400}
				{RandomPosition 1}
				{transition "273"}
				{transition "304"}
			}
			{"273"
				{position -111.343 -5151.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "274"}
				{transition "322"}
			}
			{"274"
				{position -822.805 -5217.45 0}
				{radius 400}
				{RandomPosition 1}
				{transition "275"}
			}
			{"275"
				{position -1662.74 -5383.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "276"}
			}
			{"276"
				{position -3302.18 -5419.66 0}
				{radius 400}
				{RandomPosition 1}
				{transition "277"}
			}
			{"277"
				{position -4279.87 -5376.14 0}
				{radius 400}
				{RandomPosition 1}
				{transition "278"}
			}
			{"278"
				{position -5350.4 -5366.39 0}
				{radius 400}
				{RandomPosition 1}
				{transition "279"}
			}
			{"279"
				{position -6937.26 -5340.72 0}
				{radius 400}
				{RandomPosition 1}
				{transition "280"}
			}
			{"280"
				{position -8202.66 -3986.71 0}
				{radius 400}
				{RandomPosition 1}
				{transition "281"}
			}
			{"281"
				{position -8323.23 -2380.89 0}
				{radius 400}
				{RandomPosition 1}
				{transition "282"}
			}
			{"282"
				{position -8017.71 -1094.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "283"}
			}
			{"283"
				{position -7576.48 -410.52 0}
				{radius 400}
				{RandomPosition 1}
				{transition "284"}
			}
			{"284"
				{position -6344.65 -4.09229 0}
				{radius 400}
				{RandomPosition 1}
				{transition "285"}
			}
			{"285"
				{position -5311 308.329 0}
				{radius 400}
				{RandomPosition 1}
				{transition "286"}
			}
			{"286"
				{position -4544.6 374.306 0}
				{radius 400}
				{RandomPosition 1}
				{transition "287"}
			}
			{"287"
				{position -4005.72 410.616 0}
				{radius 400}
				{RandomPosition 1}
				{transition "288"}
			}
			{"288"
				{position -3096.3 298.606 0}
				{radius 400}
				{RandomPosition 1}
				{transition "289"}
			}
			{"289"
				{position -2503.98 390.885 0}
				{radius 400}
				{RandomPosition 1}
				{transition "290"}
			}
			{"290"
				{position -1381.28 437.25 0}
				{radius 400}
				{RandomPosition 1}
				{transition "264"}
			}
			{"291"
				{position 8321.23 -4042.53 0}
				{radius 400}
				{RandomPosition 1}
				{transition "292"}
			}
			{"292"
				{position 7818.78 -3908.43 0}
				{radius 400}
				{RandomPosition 1}
				{transition "293"}
			}
			{"293"
				{position 6915.83 -3849.22 0}
				{radius 400}
				{RandomPosition 1}
				{transition "294"}
			}
			{"294"
				{position 6428.95 -3892.69 0}
				{radius 400}
				{RandomPosition 1}
				{transition "295"}
			}
			{"295"
				{position 5618.88 -4014.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "296"}
			}
			{"296"
				{position 4844.23 -4228.1 0}
				{radius 400}
				{RandomPosition 1}
				{transition "297"}
			}
			{"297"
				{position 4288.78 -4221.06 0}
				{radius 400}
				{RandomPosition 1}
				{transition "298"}
			}
			{"298"
				{position 3721.48 -3820.41 0}
				{radius 400}
				{RandomPosition 1}
				{transition "299"}
			}
			{"299"
				{position 3296.74 -3515.09 0}
				{radius 400}
				{RandomPosition 1}
				{transition "300"}
			}
			{"300"
				{position 2951.5 -3301.33 0}
				{radius 400}
				{RandomPosition 1}
				{transition "301"}
			}
			{"301"
				{position 2514.23 -3122.28 0}
				{radius 400}
				{RandomPosition 1}
				{transition "302"}
			}
			{"302"
				{position 2073.38 -3069.11 0}
				{radius 400}
				{RandomPosition 1}
				{transition "303"}
				{transition "318"}
			}
			{"303"
				{position 1184.42 -2990.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "304"}
			}
			{"304"
				{position 600.89 -2793.75 0}
				{radius 400}
				{RandomPosition 1}
				{transition "305"}
			}
			{"305"
				{position 225.462 -2573.18 0}
				{radius 400}
				{RandomPosition 1}
				{transition "306"}
			}
			{"306"
				{position -79.9014 -2154.55 0}
				{radius 400}
				{RandomPosition 1}
				{transition "307"}
			}
			{"307"
				{position -243.921 -1724.6 0}
				{radius 400}
				{RandomPosition 1}
				{transition "311"}
			}
			{"308"
				{position 3511.42 -2971.07 0}
				{radius 400}
				{RandomPosition 1}
				{transition "263"}
				{transition "266"}
				{commands
					{"entity_state"
						{tag_add freeroam}
					}
					{"delay"
						{time 1}
					}
					{"if"
						{condition
							{type cmp_i}
							{var "player_defending$"}
							{op "=="}
							{value 1}
						}
						{"action"
							{drop orders}
							{action advance}
							{target
								{source advanced}
								{group
									{select
										{tag
											{tag player}
										}
										{tag
											{tag player_veh}
										}
										{tag
											{tag player_armor}
										}
										{tag
											{tag player_car}
										}
									}
									{include
										{state
											{state operatable}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{group
									{select
										{zone
											{zone "gamezone"}
										}
									}
									{include
										{state
											{state operatable}
										}
										{relation
											{relation ally}
											{player "1"}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{amount 1
								}
							}
						}
					}
					{"if"
						{condition
							{type cmp_i}
							{var "player_defending$"}
							{op "=="}
							{value 0}
						}
						{"action"
							{drop orders}
							{action advance}
							{target
								{source advanced}
								{group
									{select
										{tag
											{tag player}
										}
										{tag
											{tag player_veh}
										}
										{tag
											{tag player_armor}
										}
										{tag
											{tag player_car}
										}
									}
									{include
										{state
											{state operatable}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{group
									{select
										{zone
											{zone "gamezone"}
										}
									}
									{include
										{relation
											{relation enemy}
											{player "1"}
										}
										{state
											{state operatable}
										}
									}
									{exclude
										{state
											{state dead}
										}
										{state
											{state inactive}
										}
									}
								}
								{amount 1
								}
							}
						}
					}
				}
			}
			{"311"
				{position -316.247 -1205.75 0}
				{radius 400}
				{RandomPosition 1}
				{transition "312"}
			}
			{"312"
				{position -324.01 -898.817 0}
				{radius 400}
				{RandomPosition 1}
				{transition "313"}
			}
			{"313"
				{position -274.328 -688.452 0}
				{radius 400}
				{RandomPosition 1}
				{transition "314"}
			}
			{"314"
				{position -481.222 -427.008 0}
				{radius 400}
				{RandomPosition 1}
				{transition "315"}
			}
			{"315"
				{position -1066.95 -185.76 0}
				{radius 400}
				{RandomPosition 1}
				{transition "316"}
			}
			{"316"
				{position -1679.65 23.6094 0}
				{radius 400}
				{RandomPosition 1}
				{transition "317"}
			}
			{"317"
				{position -2176 45.4126 0}
				{radius 400}
				{RandomPosition 1}
				{transition "266"}
			}
			{"318"
				{position 1236.5 -3893.87 0}
				{radius 400}
				{RandomPosition 1}
				{transition "319"}
			}
			{"319"
				{position 628.972 -4171.03 0}
				{radius 400}
				{RandomPosition 1}
				{transition "320"}
				{transition "276"}
			}
			{"320"
				{position -89.9858 -4221.85 0}
				{radius 400}
				{RandomPosition 1}
				{transition "321"}
			}
			{"321"
				{position -744.269 -4207.14 0}
				{radius 400}
				{RandomPosition 1}
				{transition "322"}
			}
			{"322"
				{position -1674.72 -4066.83 0}
				{radius 400}
				{RandomPosition 1}
				{transition "323"}
			}
			{"323"
				{position -2384.04 -3720.21 0}
				{radius 400}
				{RandomPosition 1}
				{transition "324"}
			}
			{"324"
				{position -2706.11 -2890.61 0}
				{radius 400}
				{RandomPosition 1}
				{transition "325"}
			}
			{"325"
				{position -2932.81 -2086.49 0}
				{radius 400}
				{RandomPosition 1}
				{transition "326"}
			}
			{"326"
				{position -3091.13 -1177.38 0}
				{radius 400}
				{RandomPosition 1}
				{transition "266"}
			}
			{"327"
				{position 8702.33 5434.65 0}
				{radius 400}
				{RandomPosition 1}
				{transition "328"}
			}
			{"328"
				{position 7840.67 5854.55 0}
				{radius 400}
				{RandomPosition 1}
				{transition "329"}
			}
			{"329"
				{position 7097.81 5860.13 0}
				{radius 400}
				{RandomPosition 1}
				{transition "330"}
			}
			{"330"
				{position 5934.22 5881.89 0}
				{radius 400}
				{RandomPosition 1}
				{transition "331"}
			}
			{"331"
				{position 4713.88 5978.42 0}
				{radius 400}
				{RandomPosition 1}
				{transition "332"}
			}
			{"332"
				{position 3485.47 5985.12 0}
				{radius 400}
				{RandomPosition 1}
				{transition "333"}
			}
			{"333"
				{position 2408.15 5899.99 0}
				{radius 400}
				{RandomPosition 1}
				{transition "334"}
			}
			{"334"
				{position 1103.26 5931.5 0}
				{radius 400}
				{RandomPosition 1}
				{transition "335"}
			}
			{"335"
				{position 523.855 5843.74 0}
				{radius 400}
				{RandomPosition 1}
				{transition "336"}
				{transition "354"}
			}
			{"336"
				{position -2236.06 5930.01 0}
				{radius 400}
				{RandomPosition 1}
				{transition "337"}
			}
			{"337"
				{position -3520.58 5856.34 0}
				{radius 400}
				{RandomPosition 1}
				{transition "338"}
				{transition "351"}
			}
			{"338"
				{position -6113.5 5745.76 0}
				{radius 400}
				{RandomPosition 1}
				{transition "339"}
			}
			{"339"
				{position -7856.77 5491.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "340"}
			}
			{"340"
				{position -8318.37 4158.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "341"}
			}
			{"341"
				{position -8743.65 3094.16 0}
				{radius 400}
				{RandomPosition 1}
				{transition "342"}
			}
			{"342"
				{position -8914.51 2244.49 0}
				{radius 400}
				{RandomPosition 1}
				{transition "343"}
			}
			{"343"
				{position -8445.91 1666.95 0}
				{radius 400}
				{RandomPosition 1}
				{transition "344"}
			}
			{"344"
				{position -7950.72 1254 0}
				{radius 400}
				{RandomPosition 1}
				{transition "345"}
			}
			{"345"
				{position -7269.41 1216.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "346"}
			}
			{"346"
				{position -6226.52 1299.7 0}
				{radius 400}
				{RandomPosition 1}
				{transition "347"}
			}
			{"347"
				{position -5502.98 1249.1 0}
				{radius 400}
				{RandomPosition 1}
				{transition "348"}
			}
			{"348"
				{position -4609.06 1081.64 0}
				{radius 400}
				{RandomPosition 1}
				{transition "349"}
			}
			{"349"
				{position -3820.62 1249.74 0}
				{radius 400}
				{RandomPosition 1}
				{transition "350"}
			}
			{"350"
				{position -3310.12 1515.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "351"}
			}
			{"351"
				{position -2872.63 1638.42 0}
				{radius 400}
				{RandomPosition 1}
				{transition "352"}
			}
			{"352"
				{position -2234.14 1566.28 0}
				{radius 400}
				{RandomPosition 1}
				{transition "353"}
				{transition "264"}
			}
			{"353"
				{position -890.623 1633.7 0}
				{radius 400}
				{RandomPosition 1}
				{transition "263"}
			}
			{"354"
				{position 79.5571 5472.06 0}
				{radius 400}
				{RandomPosition 1}
				{transition "355"}
			}
			{"355"
				{position -393.04 5214.19 0}
				{radius 400}
				{RandomPosition 1}
				{transition "356"}
			}
			{"356"
				{position -771.147 4702.53 0}
				{radius 400}
				{RandomPosition 1}
				{transition "357"}
			}
			{"357"
				{position -1045.82 4361.46 0}
				{radius 400}
				{RandomPosition 1}
				{transition "358"}
			}
			{"358"
				{position -1721.72 4114.27 0}
				{radius 400}
				{RandomPosition 1}
				{transition "265"}
			}
			{"359"
				{position 8376.59 4499.83 0}
				{radius 400}
				{RandomPosition 1}
				{transition "360"}
			}
			{"360"
				{position 7607.42 4241.58 0}
				{radius 400}
				{RandomPosition 1}
				{transition "361"}
			}
			{"361"
				{position 6850.72 4140.12 0}
				{radius 400}
				{RandomPosition 1}
				{transition "362"}
				{transition "379"}
			}
			{"362"
				{position 6106.96 3731.27 0}
				{radius 400}
				{RandomPosition 1}
				{transition "363"}
			}
			{"363"
				{position 5224.46 3421.41 0}
				{radius 400}
				{RandomPosition 1}
				{transition "364"}
			}
			{"364"
				{position 4662.15 3130.58 0}
				{radius 400}
				{RandomPosition 1}
				{transition "365"}
			}
			{"365"
				{position 4095.97 2890.4 0}
				{radius 400}
				{RandomPosition 1}
				{transition "366"}
			}
			{"366"
				{position 3636.97 2596.92 0}
				{radius 400}
				{RandomPosition 1}
				{transition "367"}
			}
			{"367"
				{position 3169.5 2294.08 0}
				{radius 400}
				{RandomPosition 1}
				{transition "368"}
			}
			{"368"
				{position 2868.77 1984.37 0}
				{radius 400}
				{RandomPosition 1}
				{transition "369"}
			}
			{"369"
				{position 2385.42 1708.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "370"}
			}
			{"370"
				{position 1909.89 1589.77 0}
				{radius 400}
				{RandomPosition 1}
				{transition "371"}
				{transition "374"}
			}
			{"371"
				{position 1477.77 1483.92 0}
				{radius 400}
				{RandomPosition 1}
				{transition "372"}
			}
			{"372"
				{position 972.784 1207 0}
				{radius 400}
				{RandomPosition 1}
				{transition "373"}
			}
			{"373"
				{position 534.887 915.06 0}
				{radius 400}
				{RandomPosition 1}
				{transition "264"}
			}
			{"374"
				{position 959.199 1623.05 0}
				{radius 400}
				{RandomPosition 1}
				{transition "375"}
			}
			{"375"
				{position 340.075 1588.62 0}
				{radius 400}
				{RandomPosition 1}
				{transition "376"}
			}
			{"376"
				{position -220.536 1556.18 0}
				{radius 400}
				{RandomPosition 1}
				{transition "377"}
			}
			{"377"
				{position -880.492 1486.98 0}
				{radius 400}
				{RandomPosition 1}
				{transition "378"}
			}
			{"378"
				{position -1536.95 1370.64 0}
				{radius 400}
				{RandomPosition 1}
				{transition "266"}
			}
			{"379"
				{position 5812.22 4337.28 0}
				{radius 400}
				{RandomPosition 1}
				{transition "380"}
			}
			{"380"
				{position 4673.81 4263.67 0}
				{radius 400}
				{RandomPosition 1}
				{transition "381"}
			}
			{"381"
				{position 4126.57 4149.47 0}
				{radius 400}
				{RandomPosition 1}
				{transition "382"}
			}
			{"382"
				{position 2704.11 3913.64 0}
				{radius 400}
				{RandomPosition 1}
				{transition "383"}
				{transition "395"}
			}
			{"383"
				{position 1454.3 4089.93 0}
				{radius 400}
				{RandomPosition 1}
				{transition "384"}
			}
			{"384"
				{position 628.93 3957.13 0}
				{radius 400}
				{RandomPosition 1}
				{transition "385"}
			}
			{"385"
				{position -328.597 3538.87 0}
				{radius 400}
				{RandomPosition 1}
				{transition "386"}
			}
			{"386"
				{position -1193.64 3047.64 0}
				{radius 400}
				{RandomPosition 1}
				{transition "387"}
			}
			{"387"
				{position -2153.75 2374.23 0}
				{radius 400}
				{RandomPosition 1}
				{transition "266"}
			}
			{"388"
				{position 8574.76 2450.67 0}
				{radius 400}
				{RandomPosition 1}
				{transition "389"}
			}
			{"389"
				{position 7793.23 2966.97 0}
				{radius 400}
				{RandomPosition 1}
				{transition "390"}
				{transition "333"}
			}
			{"390"
				{position 6815.19 3209.3 0}
				{radius 400}
				{RandomPosition 1}
				{transition "391"}
			}
			{"391"
				{position 5727.54 3428.96 0}
				{radius 400}
				{RandomPosition 1}
				{transition "392"}
			}
			{"392"
				{position 5114.53 3494.68 0}
				{radius 400}
				{RandomPosition 1}
				{transition "393"}
			}
			{"393"
				{position 3271.61 3313.47 0}
				{radius 400}
				{RandomPosition 1}
				{transition "394"}
				{transition "385"}
			}
			{"394"
				{position 2166.29 3151 0}
				{radius 400}
				{RandomPosition 1}
				{transition "395"}
			}
			{"395"
				{position 226.191 2692.69 0}
				{radius 400}
				{RandomPosition 1}
				{transition "396"}
			}
			{"396"
				{position -946.988 2299.96 0}
				{radius 400}
				{RandomPosition 1}
				{transition "397"}
			}
			{"397"
				{position -1701.07 2150.25 0}
				{radius 400}
				{RandomPosition 1}
				{transition "398"}
			}
			{"398"
				{position -3469.95 1733.04 0}
				{radius 400}
				{RandomPosition 1}
				{transition "399"}
			}
			{"399"
				{position -4361.32 829.9 0}
				{radius 400}
				{RandomPosition 1}
				{transition "400"}
			}
			{"400"
				{position -4778.04 232.184 0}
				{radius 400}
				{RandomPosition 1}
				{transition "401"}
			}
			{"401"
				{position -4693.23 -435.306 0}
				{radius 400}
				{RandomPosition 1}
				{transition "402"}
			}
			{"402"
				{position -4522.28 -1289.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "403"}
			}
			{"403"
				{position -3867.76 -2655.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "404"}
			}
			{"404"
				{position -2895.44 -3532.96 0}
				{radius 400}
				{RandomPosition 1}
				{transition "405"}
			}
			{"405"
				{position -1595.02 -3355.8 0}
				{radius 400}
				{RandomPosition 1}
				{transition "406"}
			}
			{"406"
				{position -19.2822 -3490.7 0}
				{radius 400}
				{RandomPosition 1}
				{transition "308"}
			}
			{"407"
				{position 8694.97 1697.24 0}
				{radius 400}
				{RandomPosition 1}
				{transition "408"}
				{transition "444"}
			}
			{"408"
				{position 7459.87 1732.97 0}
				{radius 400}
				{RandomPosition 1}
				{transition "409"}
			}
			{"409"
				{position 6729.92 1676.92 0}
				{radius 400}
				{RandomPosition 1}
				{transition "410"}
			}
			{"410"
				{position 6011.16 1711.95 0}
				{radius 400}
				{RandomPosition 1}
				{transition "411"}
			}
			{"411"
				{position 5499.95 1723.15 0}
				{radius 400}
				{RandomPosition 1}
				{transition "412"}
			}
			{"412"
				{position 4783.54 1639.33 0}
				{radius 400}
				{RandomPosition 1}
				{transition "413"}
			}
			{"413"
				{position 4264.59 1267.33 0}
				{radius 400}
				{RandomPosition 1}
				{transition "414"}
			}
			{"414"
				{position 3329.05 837.68 0}
				{radius 400}
				{RandomPosition 1}
				{transition "415"}
			}
			{"415"
				{position 2658.27 529.402 0}
				{radius 400}
				{RandomPosition 1}
				{transition "416"}
				{transition "419"}
			}
			{"416"
				{position 2644.51 -52.3969 0}
				{radius 400}
				{RandomPosition 1}
				{transition "417"}
			}
			{"417"
				{position 2683.98 -843.878 0}
				{radius 400}
				{RandomPosition 1}
				{transition "418"}
			}
			{"418"
				{position 2666.24 -1441.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "308"}
			}
			{"419"
				{position 2034.55 289.328 0}
				{radius 400}
				{RandomPosition 1}
				{transition "420"}
			}
			{"420"
				{position 1509.74 60.7797 0}
				{radius 400}
				{RandomPosition 1}
				{transition "421"}
			}
			{"421"
				{position 856.096 27.0258 0}
				{radius 400}
				{RandomPosition 1}
				{transition "264"}
			}
			{"422"
				{position 8813.48 -1458.59 0}
				{radius 400}
				{RandomPosition 1}
				{transition "423"}
			}
			{"423"
				{position 8319.61 -1757.12 0}
				{radius 400}
				{RandomPosition 1}
				{transition "424"}
			}
			{"424"
				{position 7852.61 -1948.74 0}
				{radius 400}
				{RandomPosition 1}
				{transition "425"}
			}
			{"425"
				{position 7258.31 -2172.01 0}
				{radius 400}
				{RandomPosition 1}
				{transition "426"}
			}
			{"426"
				{position 6480.55 -2442.23 0}
				{radius 400}
				{RandomPosition 1}
				{transition "427"}
			}
			{"427"
				{position 6079.66 -2547.86 0}
				{radius 400}
				{RandomPosition 1}
				{transition "428"}
			}
			{"428"
				{position 5036.36 -2789.53 0}
				{radius 400}
				{RandomPosition 1}
				{transition "308"}
				{transition "429"}
			}
			{"429"
				{position 4448.47 -3275.01 0}
				{radius 400}
				{RandomPosition 1}
				{transition "430"}
			}
			{"430"
				{position 4016.56 -3641.32 0}
				{radius 400}
				{RandomPosition 1}
				{transition "431"}
			}
			{"431"
				{position 3750.88 -3965.26 0}
				{radius 400}
				{RandomPosition 1}
				{transition "432"}
			}
			{"432"
				{position 2927.53 -4306.44 0}
				{radius 400}
				{RandomPosition 1}
				{transition "433"}
			}
			{"433"
				{position 2180.23 -4351.31 0}
				{radius 400}
				{RandomPosition 1}
				{transition "434"}
			}
			{"434"
				{position 1288.43 -4358.99 0}
				{radius 400}
				{RandomPosition 1}
				{transition "435"}
			}
			{"435"
				{position 1.1748 -3930.66 0}
				{radius 400}
				{RandomPosition 1}
				{transition "436"}
			}
			{"436"
				{position -891.652 -3484.18 0}
				{radius 400}
				{RandomPosition 1}
				{transition "437"}
			}
			{"437"
				{position -1781.84 -3132.6 0}
				{radius 400}
				{RandomPosition 1}
				{transition "438"}
			}
			{"438"
				{position -2067.91 -2402.4 0}
				{radius 400}
				{RandomPosition 1}
				{transition "439"}
			}
			{"439"
				{position -2357.38 -1182.55 0}
				{radius 400}
				{RandomPosition 1}
				{transition "266"}
			}
			{"440"
				{position 8637.35 -857.169 0}
				{radius 400}
				{RandomPosition 1}
				{transition "441"}
			}
			{"441"
				{position 8172.17 -771.268 0}
				{radius 400}
				{RandomPosition 1}
				{transition "442"}
			}
			{"442"
				{position 7527.21 -699.592 0}
				{radius 400}
				{RandomPosition 1}
				{transition "443"}
			}
			{"443"
				{position 7137.63 -701.833 0}
				{radius 400}
				{RandomPosition 1}
				{transition "444"}
				{transition "413"}
			}
			{"444"
				{position 6631.44 -720.415 0}
				{radius 400}
				{RandomPosition 1}
				{transition "445"}
				{transition "457"}
			}
			{"445"
				{position 6078.52 -849.322 0}
				{radius 400}
				{RandomPosition 1}
				{transition "446"}
			}
			{"446"
				{position 5232.86 -925.782 0}
				{radius 400}
				{RandomPosition 1}
				{transition "447"}
			}
			{"447"
				{position 4423.03 -1006.06 0}
				{radius 400}
				{RandomPosition 1}
				{transition "448"}
			}
			{"448"
				{position 3420.6 -949.734 0}
				{radius 400}
				{RandomPosition 1}
				{transition "449"}
			}
			{"449"
				{position 2649.47 -861.459 0}
				{radius 400}
				{RandomPosition 1}
				{transition "450"}
			}
			{"450"
				{position 1991.01 -907.894 0}
				{radius 400}
				{RandomPosition 1}
				{transition "451"}
			}
			{"451"
				{position 1139.1 -1000.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "452"}
			}
			{"452"
				{position 453.26 -953.487 0}
				{radius 400}
				{RandomPosition 1}
				{transition "453"}
			}
			{"453"
				{position -404.23 -1022.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "454"}
			}
			{"454"
				{position -1119.6 -1062.6 0}
				{radius 400}
				{RandomPosition 1}
				{transition "455"}
			}
			{"455"
				{position -1599.5 -902.126 0}
				{radius 400}
				{RandomPosition 1}
				{transition "456"}
			}
			{"456"
				{position -1827.87 -417.82 0}
				{radius 400}
				{RandomPosition 1}
				{transition "265"}
			}
			{"457"
				{position 5584.93 -590.743 0}
				{radius 400}
				{RandomPosition 1}
				{transition "458"}
			}
			{"458"
				{position 4968.96 -436.219 0}
				{radius 400}
				{RandomPosition 1}
				{transition "459"}
			}
			{"459"
				{position 4297.73 -419.202 0}
				{radius 400}
				{RandomPosition 1}
				{transition "460"}
			}
			{"460"
				{position 3327 -456.852 0}
				{radius 400}
				{RandomPosition 1}
				{transition "461"}
			}
			{"461"
				{position 2517.23 -438.801 0}
				{radius 400}
				{RandomPosition 1}
				{transition "462"}
			}
			{"462"
				{position 1958.67 -484.677 0}
				{radius 400}
				{RandomPosition 1}
				{transition "463"}
			}
			{"463"
				{position 1423.87 -567.787 0}
				{radius 400}
				{RandomPosition 1}
				{transition "464"}
			}
			{"464"
				{position 720.662 -472.843 0}
				{radius 400}
				{RandomPosition 1}
				{transition "264"}
			}
		}
		{waypoints "startingwaypoint"
			{"1001"
				{position -9600.71 -4972.95 0}
				{radius 500}
				{RandomPosition 1}
				{transition "33"}
				{transition "70"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"1002"
				{position -9788.12 -1686.82 0}
				{radius 500}
				{RandomPosition 1}
				{transition "99"}
				{transition "148"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"1003"
				{position -9587.51 1230.75 0}
				{radius 500}
				{RandomPosition 1}
				{transition "172"}
				{transition "205"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"1004"
				{position -9572.1 4970.81 0}
				{radius 500}
				{RandomPosition 1}
				{transition "212"}
				{transition "248"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"2001"
				{position 9258.36 4821.39 0}
				{radius 500}
				{RandomPosition 1}
				{transition "327"}
				{transition "359"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"2002"
				{position 9441.86 1792.34 0}
				{radius 500}
				{RandomPosition 1}
				{transition "388"}
				{transition "407"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"2003"
				{position 9204.97 -1005.4 0}
				{radius 500}
				{RandomPosition 1}
				{transition "422"}
				{transition "440"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
			{"2004"
				{position 9079.03 -4677.56 0}
				{radius 500}
				{RandomPosition 1}
				{transition "267"}
				{transition "291"}
				{commands
					{"entity_state"
						{tag_add squad}
					}
				}
			}
		}
		{waypoints "paradrop"
			{"21"
				{position 1504.61 -7728.37 0}
			}
			{"23"
				{position 8029.72 -5680.81 0}
			}
			{"247"
				{position 335.942 -7532.23 0}
			}
			{"249"
				{position -3172.6 -8101.78 0}
			}
			{"25"
				{position -7966.55 -5897.11 0}
			}
			{"27"
				{position -6092.42 -7946.43 0}
			}
			{"3000"
				{position 1508.17 -8477.38 0}
				{transition "21"}
			}
			{"3001"
				{position 8311.7 -6589.09 0}
				{transition "23"}
			}
			{"3002"
				{position -8019.13 -6795.9 0}
				{transition "25"}
			}
			{"3003"
				{position 130.421 -8292.67 0}
				{transition "247"}
			}
			{"3004"
				{position -3220.76 -9002.42 0}
				{transition "249"}
			}
			{"3005"
				{position -8805.15 -8077.04 0}
				{transition "468"}
			}
			{"3006"
				{position -6358.99 -9121.12 0}
				{transition "27"}
			}
			{"3007"
				{position 6737.18 -8586.07 0}
				{transition "34"}
			}
			{"3008"
				{position -8357.36 7412.06 0}
				{transition "36"}
			}
			{"3009"
				{position 8812.21 6885.16 0}
				{transition "470"}
			}
			{"3010"
				{position -2636.2 8725.47 0}
				{transition "472"}
			}
			{"3011"
				{position -5148.35 9048.77 0}
				{transition "474"}
			}
			{"3012"
				{position -8953.96 8720.26 0}
				{transition "476"}
			}
			{"3013"
				{position 3301.93 8854.77 0}
				{transition "478"}
			}
			{"3014"
				{position 5811.05 9174.56 0}
				{transition "480"}
			}
			{"3015"
				{position 55.4998 8744.24 0}
				{transition "482"}
			}
			{"3100"
				{position 390.883 -9045.02 0}
				{radius 4000}
				{RandomPosition 1}
				{commands
					{"delete"}
				}
			}
			{"3101"
				{position -1120.36 9920.27 0}
				{radius 4000}
				{RandomPosition 1}
				{commands
					{"delete"}
				}
			}
			{"34"
				{position 6472.6 -7378.52 0}
			}
			{"36"
				{position -7867 6108.68 0}
			}
			{"468"
				{position -8024.05 -7041.4 0}
			}
			{"470"
				{position 8837.04 6080.14 0}
			}
			{"472"
				{position -3006.1 7211.6 0}
			}
			{"474"
				{position -4863.45 7181.31 0}
			}
			{"476"
				{position -8841.31 8106.65 0}
			}
			{"478"
				{position 3053.79 7485.35 0}
			}
			{"480"
				{position 5644.47 7317.28 0}
			}
			{"482"
				{position 202.197 7598.48 0}
			}
		}
		{waypoints "teleportdefense"
			{"4000"
				{position 573.975 -2132.4 0}
				{radius 2000}
				{RandomPosition 1}
			}
		}
		{waypoints "spawn_points"
			{"5001"
				{position 10403.7 4995.22 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"5002"
				{position 10459.2 2081.43 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"5003"
				{position 10439.1 -945.243 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"5004"
				{position 10372.9 -4633.76 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"6001"
				{position -10898.4 -4809.14 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"6002"
				{position -10849.1 -1914.52 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"6003"
				{position -10876.8 1150.59 0}
				{radius 400}
				{RandomPosition 1}
			}
			{"6004"
				{position -10875.3 4950.26 0}
				{radius 400}
				{RandomPosition 1}
			}
		}
	
